// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywkkgmxetdmxutdbmvsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3a2tnbXhldGRteHV0ZGJtdnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODE0ODksImV4cCI6MjA2NTU1NzQ4OX0.pC2MkMYfU8tIyXrBLNCBZfev1XfvTjZBYtNhsFc4xi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);